export const GET_CHANNELS = 'GET_CHANNELS';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const GET_CHANNEL = 'GET_CHANNEL';

export const SET_USERNAME = 'SET_USERNAME';
export const GET_USERNAME = 'GET_USERNAME';
